[project]
name = "aioclamd"
version = "1.1.0"
description = "Asynchronous client for virus scanning with ClamAV"
authors = [{name = "Henrik Blidh", email = "henrik.blidh@nedomkull.com"}]
readme = "README.md"
license = "MIT"
requires-python = ">=3.9"
keywords = ["clamav", "virus", "scanning"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
dependencies = []

[project.urls]
Homepage = "https://github.com/hbldh/aioclamd"
Repository = "https://github.com/hbldh/aioclamd"

[project.optional-dependencies]
lint = ["black>=22.8.0", "flake8>=5.0.0"]
test = ["pytest>=7.1.3", "pytest-asyncio>=0.19.0", "pytest-cov>=3.0.0"]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["aioclamd"]
